### ISSUE TITLE
Country pull down field

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#1046]
The pull-down country field doesn't feel right. It is different from the other input fields (CSS wise).

<img width="1524" alt="Bildschirmfoto 2024-09-13 um 18 48 35" src="https://github.com/user-attachments/assets/bf7f63bd-6536-4945-8d38-e835980c6d9a">

Please have a look at this HTML:
```html
<div class="mt-2 sm:col-span-2 sm:mt-0">
              <select id="country" name="country" autocomplete="country-name" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6">
                <option>United States</option>
                <option>Canada</option>
                <option>Mexico</option>
              </select>
            </div>
```

And this field shouldn't have the initial focus. AND it should default to Germany.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , it seems it is a style native to the select element , since we only have germany at the moment , are you open to having a text input , that is read only and defaults to `Germany` . I have this now , but still looks off

![Screenshot 2024-09-15 at 10 16 53](https://github.com/user-attachments/assets/de3073bf-fb00-476c-b764-8b8d7798012f)

**Comment by wintermeyer** [comment]
It is off but better than before. Please ask a question about it on stackoverflow.com and add a link to that here. I am pretty sure that there is a good solution for the given problem within the TailwindCSS universe.

Worst case: This is good for now.
