### ISSUE TITLE
Text box resized to default height after every Enter

### ISSUE THREAD

**Issue by agds3** [wintermeyer/animina#1077]
Description:
Text box is resized to default height after every Enter key stroke.

Steps to reproduce: 
- add a new story
- increase height of text box for content
- click in the text box and press Enter
  (or write some text and press Enter)

Expected behavior:
Height should be unchanged.

Browser: Firefox 130, Linux

**Comment by wintermeyer** [comment]
@agds3 Thanks for the bug report!

**Comment by Kimutai01** [comment]
@wintermeyer 
Is it okay if I use JavaScript for this?

**Comment by wintermeyer** [comment]
Please elaborate what you want to do.

**Comment by wintermeyer** [comment]
An other way to go: Can we deactivate the possibility to resize the text box?

**Comment by Kimutai01** [comment]
https://github.com/user-attachments/assets/9916768c-5243-42b1-b402-8918cb9d097f

So right now it still resizes...but the difference is it is resized to where the content reaches and this makes sense. Since it won't be confusing and it will take you back to where the cursor was unlike the other one

The video below shows how it was initially

https://github.com/user-attachments/assets/63894f97-5262-4d47-b285-d394e09ab9cf

Now I'm using Javascript to adjust the height based on the text content so that you can see all the text.

**Comment by Kimutai01** [comment]
> An other way to go: Can we deactivate the possibility to resize the text box?

This is also an option but I feel it would be better for a user if they can see the whole text that they have written

**Comment by wintermeyer** [comment]
> > An other way to go: Can we deactivate the possibility to resize the text box?
> 
> This is also an option but I feel it would be better for a user if they can see the whole text that they have written

Please deactivate the possibility to reize the text box. That is the way which is the easiest to support right now.

But make the text box 3 rows larger on the desktop. We have the real estate to support that.
