### ISSUE TITLE
Add validations to select unique red and green color flags for the user.

### ISSUE THREAD

**Issue by MICHAELMUNAVU83** [wintermeyer/animina#261]
- Currently a user can pick "honesty" both as a red flag and as a green flag , we should have a validation to fix this

**Comment by wintermeyer** [comment]
On both sides of the table. So if I select a green flag it should validate that there is not already a red one and vice versa. Add a test for a better night sleep.

GUI wise we should deactivate those flags in the profile creating workflow which are already picked by the other colour and put a green or red dot in the flag (right side). So that a user sees "Oh ... this flag is deactivated. I can't select it. And ... Ahhh! because it is already a red flag."

**Comment by MICHAELMUNAVU83** [comment]
I will break this down into 2 issues , one for the GIU and the other one for context and validations
