### ISSUE TITLE
New stories don't show up

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#282]
When I create a new story it doesn't get displayed afterwards in my profile.

![ScreenFlow](https://github.com/animina-dating/animina/assets/69770/88e5f5b7-8cf0-4515-b9ff-908ead4df5ee)

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , this fails because of this function


```
defp fetch_stories_and_flags(user, language) do
    stories = fetch_stories(user.id)

    chunks_flags =
      fetch_flags(user.id, :white, language)
      |> Enum.chunk_every(5)

    Enum.zip(stories, chunks_flags)
  end
```

With this , we are faced with a situation where if we have 2 stories , there needs to be  at least 10 white flags selected for you to see the stories , if we have it as such
```
defp fetch_stories_and_flags(user, language) do
    stories = fetch_stories(user.id)

    flags =
      fetch_flags(user.id, :white, language)

    length_of_flags = length(flags)
    

    cond do
      length_of_flags >= 5 ->
        chunks_flags = Enum.chunk_every(flags, 5)
        Enum.zip(stories, chunks_flags)

      length_of_flags == 0 ->
        Enum.map(stories, fn story ->
          {
            story,
            []
          }
        end)

      length_of_flags <= 5 ->
        chunks_flags = Enum.chunk_every(flags, 1)

        Enum.map(stories, fn story ->
          {
            story,
            chunks_flags
          }
        end)
    end
  end
```

This would have it that we display  number of stories similar to that of flags .
If you have 0-5 flags , we display that number of stories even if you have more than that in the database .
You may have 20 stories , but if you have 5 white flags , we only show 5 stories

**Comment by wintermeyer** [comment]
Quick fix and dirty fix: Add 5 times the number of stories as nil items to the list of flags before chunking it.

**Comment by MICHAELMUNAVU83** [comment]
This would work
