### ISSUE TITLE
Profile doesn't have the correct URL when coming from bookmarks

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#456]
When I click on a bookmark link of a profile the profile gets rendered but the URL is wrong it shows the current_user slag and not that of the profile.

![bookmark](https://github.com/animina-dating/animina/assets/69770/dd2b7f31-a40a-498f-8891-75152f2aa437)

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , Just tried this , it is because on the Profile page , we are displaying the `name` and not the `username` so it may get confusing mostly if the name and username generated by `mix create_dummy_accounts 10` are different.
So you may find the username is `nora.franecki` but the name is `Avis Absire`

 I believe this works , you can confirm from your side if it is so.

**Comment by wintermeyer** [comment]
Ahhhh... how dumb I am! Sorry! I should have thought about that.

Please don't hesitate to close this kind of issue with such a comment.
