### ISSUE TITLE
Validate unique mobile phone number

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#49]
See #48. Same problem.

**Comment by philipp-kempgen** [comment]
The "Mobile phone number" input field lets me enter "abcde".
The validation should probably make sure, that this field is a valid phone number, i.e. heavily restrict the allowed characters, and then *normalize* the phone number.

Normalization is necessary so we don't end up with "0123-456789", "0123 456789", "0123456789" and "+49123456789", which is essentially the same phone number.

We also need to make sure not to bombard emergency numbers etc. with text messages.
And we probably don't want to send text messages to expensive foreign numbers.

Realistically, we need to use some API here to send text messages.
The provider would be in Germany for now.

I.e. for now I would allow `/\A[0-9+ \-]+\z/`, then (server side?):
- strip "boring" stuff, i.e. strip "`(0)`", then strip "` `" and "`-`",
- then normalize the phone number by converting leading "`00`" to "`+`",
- then strip a leading "`0`" if any,
- then add country prefix "`+49`" if the phone number doesn't start in "`+`",
- then (server side) validate that the phone number is `/\A(?<country_code>\+49)[1][0-9]{9,13}\z/`

I hope I didn't forget anything.

This may also need some rate-limiting mechanism.

And the second step should ask for a 6-digit code received by text message.

And it needs a way to trigger a retransmission, as text messages may get lost.

We may even want to remove the "verification code" thing for now, because this isn't an easy thing to get right.

**Comment by philipp-kempgen** [comment]
Oh, and it would need to work in **development mode** without actually sending text messages to a cell phone number and by allowing e.g. "000000" as verification.

Not a trivial thing, overall.

**Comment by wintermeyer** [comment]
> Oh, and it would need to work in **development mode** without actually sending text messages to a cell phone number and by allowing e.g. "000000" as verification.

Right now we do not send any verification text messages. That is going to be a future feature.

**Comment by philipp-kempgen** [comment]
> Right now we do not send any verification text messages. That is going to be a future feature.

I know. But the input field says „Mobile phone number (to receive a verification code)“, which – to me – makes it seem like I should receive a verification code via text message during the registration.

That's why I was proposing to either actually implement the feature (and also think about development mode), or to change the wording as not to confuse the user, or to remove that feature for now and implement 2FA later.

**Comment by wintermeyer** [comment]
@philipp-kempgen I hear you. But I disagree. "to receive a verification code" doesn't mean that we are sending one right away. But it makes it more likely that user enter their real mobile phone number.

I'll sleep over it.
