### ISSUE TITLE
PotentialPartner resource

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#632]
## The problem

We need a way to find and to handle potential partners. Right now we do have a function which fetches new ones out of the database. But for /my/dashboard we need a way to display 4 potential partners, remember them and to have a reload/refetch functionality. And all this has to work too for the 3rd party API.

## The idea

Let's add a `PotentialPartner` resource which belongs to the user and the potential_partner. And it should have a `position` attribute to sort it. 1 being the best fit. 4 the worst. Rules have to be in place that only the user/owner and admins can read this. Nobody should be able to create, update or delete it. Only the animina core does that. Not a human. But there has to be a `refresh` or `reload` action which the user can trigger to get 4 new potential_partners. For that the user has to pay 20 points. No points: No refresh!

We could use an additional `is_active` boolean to filter out old potential_partners while not having to delete them. Plus the usual timestamps.

## The reload

When a reload is triggered we have to use the already existing function to fetch 4 new potential partners and put them into the resource. We have to add a logic that we don't fetch ones we already loaded in the past. Only if we ran out of potential partners we recycle the old ones.

# The dashboard

The darshboard will display the `is_active == true` once. If the list is empty it will try to reload (if enough points are there to do this).

**Comment by MICHAELMUNAVU83** [comment]
Very interesting idea @wintermeyer  , storing it in the DB ensures we can keep track of already viewed potential partners . 
Correct me if I am wrong , if I hit refresh , 4 more records are added to the table and we show the most recent ones? Also what would be the criteria for selection of positions , how would we know who is the best fit and worst?

**Comment by wintermeyer** [comment]
If I hit refresh 4 more are fetched plus the 4 before become inactive. 

About position: Just add it as it comes from the database. That is a can we kick down the road but I’d like to have the functionality already in place.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , question , I have a total of 5 potentials from the query . On first mount , animina adds 4 to the PotentialPartner resource , so now I have 1 potential in the query that is not in the resource table , what should happen when  I refresh ? Should I make the 4 previous inactive and display the next 1 that was not in the resource but was added on refresh . Another thing we need to think about is how we should display all potentials . Maybe instead of a refresh , we have a + button , that adds to your list of potentials and we now display them in the order they were created at
