### ISSUE TITLE
Missing password recovery.

### ISSUE THREAD

**Issue by proxemy** [wintermeyer/animina#977]
I recently created a new account and stored the credentials in my password manager, as usual. I then set up my profile details after following the link from the confirmation mail.

One day later I realized that my profile picture is showed on the home screen, so I wanted to login an make my profile non-public. All I got was a “wrong login credentials” message and I am not able to find a “reset my password” link.

Further more, when I click on my listed profile (not signed in), I get the message:
„This profile either doesn't exist or you don't have enough points to access it.
You need 20 points to access a .“ (white space and dot at the end as is)
so maybe something went wrong with my profile creation.

Thank you for your time.

**Comment by wintermeyer** [comment]
> Further more, when I click on my listed profile (not signed in), I get the message:
„This profile either doesn't exist or you don't have enough points to access it.
You need 20 points to access a .“ (white space and dot at the end as is)
so maybe something went wrong with my profile creation.

This means that your profile is not public. So non animina members can not see it.

@MICHAELMUNAVU83 We should change the message so that the 20 points are not mentioned if somebody is not logged in.
